services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  dagster:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
    ports:
      - "3000:3000"
    command: dagster dev -h 0.0.0.0 -p 3000 -m dags.telepharm_pipeline



volumes:
  pgdata:
